spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:parkinglot
    username: Lester
    password: Lester0090
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console.enabled: true
server:
  port: 8888
